[package]
name = "aruntime"
version = "0.1.0"
edition = "2021"

[dependencies]
polling = "2"
socket2 = "0.4"
libc = "0.2"
nix = "0.23"
scoped-tls = "1"
futures = "0.3"
waker-fn = "1"
pin-utils = "0.1"
rustc-hash = "1"
io-uring = "0.6"